### ISSUE TITLE
Remove bindgen dependancy?

### ISSUE THREAD

**Issue by hakanols** [42-technology-ltd/nrf9160-demo#4]
I am new to Rust so take my suggestion with a huge grain of salt.
To simplify for new users it would be great to remove the clang and bindgen dependency.

I have noticed that issue that is listed as the reason for bindgen in https://github.com/thejpster/nrfxlib-sys is closed:
https://github.com/rust-lang/cargo/issues/5730

Guess Cargo issue 5730 not solving the problem but should it not be possible to solve this with something precompiled like they do in:
https://github.com/rusqlite/rusqlite#binding-generation

BR Håkan

**Comment by jonathanpallant** [comment]
Has #5730 made it through to stable? If so, I'm happy to turn bindgen back into a build time dependency.

I considered precompilation, but I'm not a fan in general, as it's far too easy for the compiled objects and the source code to get out of step.

**Comment by hakanols** [comment]
You are correct.  #5730 has not made it to stable at the time of writing. My bad.

You are more knowledgable on the subject of precompiling for Rust than me.

BR
