### ISSUE TITLE
not building

### ISSUE THREAD

**Issue by macthestack** [42-technology-ltd/nrf9160-demo#5]
When I try to build I get:

error: no matching package named `actinius-icarus-bsp` found
location searched: https://github.com/nrf-rs/nrf52-hal

I would love to try rust on the nrf9160 and this repo seems like the best starting point but I can't get it to work.

**Comment by jonathanpallant** [comment]
I believe the BSP for that board has moved to https://github.com/nrf-rs/actinius-icarus. You'll need to update the `Cargo.toml` to point there instead.

**Comment by macthestack** [comment]
Thanks @jonathanpallant !
